# ruff
[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint]
ignore = ["ALL"]

# mypy
[tool.mypy]
plugins = ["mypy_django_plugin.main"]

[tool.django-stubs]
django_settings_module = "core.settings"
